package edu.maranatha.pbol.model.pojo;
// Generated May 12, 2016 9:02:47 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pemasukan generated by hbm2java
 */
@Entity
@Table(name="pemasukan"
    ,catalog="moneymanager"
)
public class Pemasukan  implements java.io.Serializable {


     private Integer idpemasukan;
     private User user;
     private int nominal;
     private Date tanggalpemasukan;
     private String keterangan;

    public Pemasukan() {
    }

    public Pemasukan(User user, int nominal, Date tanggalpemasukan, String keterangan) {
       this.user = user;
       this.nominal = nominal;
       this.tanggalpemasukan = tanggalpemasukan;
       this.keterangan = keterangan;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpemasukan", unique=true, nullable=false)
    public Integer getIdpemasukan() {
        return this.idpemasukan;
    }
    
    public void setIdpemasukan(Integer idpemasukan) {
        this.idpemasukan = idpemasukan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iduser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="nominal", nullable=false)
    public int getNominal() {
        return this.nominal;
    }
    
    public void setNominal(int nominal) {
        this.nominal = nominal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tanggalpemasukan", nullable=false, length=19)
    public Date getTanggalpemasukan() {
        return this.tanggalpemasukan;
    }
    
    public void setTanggalpemasukan(Date tanggalpemasukan) {
        this.tanggalpemasukan = tanggalpemasukan;
    }

    
    @Column(name="keterangan", nullable=false, length=65535)
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }




}


