package edu.maranatha.pbol.model.pojo;
// Generated May 12, 2016 9:02:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="moneymanager"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String nama;
     private String alamat;
     private String nohp;
     private String jeniskelamin;
     private Set<Agenda> agendas = new HashSet<Agenda>(0);
     private Set<Pengeluaran> pengeluarans = new HashSet<Pengeluaran>(0);
     private Set<Pemasukan> pemasukans = new HashSet<Pemasukan>(0);

    public User() {
    }

	
    public User(String username, String password, String nama, String alamat, String nohp, String jeniskelamin) {
        this.username = username;
        this.password = password;
        this.nama = nama;
        this.alamat = alamat;
        this.nohp = nohp;
        this.jeniskelamin = jeniskelamin;
    }
    public User(String username, String password, String nama, String alamat, String nohp, String jeniskelamin, Set<Agenda> agendas, Set<Pengeluaran> pengeluarans, Set<Pemasukan> pemasukans) {
       this.username = username;
       this.password = password;
       this.nama = nama;
       this.alamat = alamat;
       this.nohp = nohp;
       this.jeniskelamin = jeniskelamin;
       this.agendas = agendas;
       this.pengeluarans = pengeluarans;
       this.pemasukans = pemasukans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="nama", nullable=false, length=100)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="alamat", nullable=false, length=65535)
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="nohp", nullable=false, length=20)
    public String getNohp() {
        return this.nohp;
    }
    
    public void setNohp(String nohp) {
        this.nohp = nohp;
    }

    
    @Column(name="jeniskelamin", nullable=false, length=30)
    public String getJeniskelamin() {
        return this.jeniskelamin;
    }
    
    public void setJeniskelamin(String jeniskelamin) {
        this.jeniskelamin = jeniskelamin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Pengeluaran> getPengeluarans() {
        return this.pengeluarans;
    }
    
    public void setPengeluarans(Set<Pengeluaran> pengeluarans) {
        this.pengeluarans = pengeluarans;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Pemasukan> getPemasukans() {
        return this.pemasukans;
    }
    
    public void setPemasukans(Set<Pemasukan> pemasukans) {
        this.pemasukans = pemasukans;
    }




}


